<?php

if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_classes-fields',
		'title' => 'Classes Fields',
		'fields' => array (
			array (
				'key' => 'field_534f40f442ab7',
				'label' => 'Days',
				'name' => 'days',
				'type' => 'text',
				'required' => 1,
				'default_value' => 'By Appointment',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_534f41af42ab8',
				'label' => 'Times',
				'name' => 'times',
				'type' => 'text',
				'instructions' => 'Leave blank if "By Appointment"',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_534f4352383bf',
				'label' => 'Location',
				'name' => 'location',
				'type' => 'text',
				'default_value' => 'The Cirque Lab',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_534f4363383c0',
				'label' => 'Location Link',
				'name' => 'location_url',
				'type' => 'text',
				'instructions' => 'Use http://bellinghamcircusguild.com/location for the cirque lab. Otherwise a google maps link or venue website.',
				'default_value' => 'http://bellinghamcircusguild.com/location',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_534f421142ab9',
				'label' => 'Cost',
				'name' => 'cost',
				'type' => 'text',
				'default_value' => 'By individual contract',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_534f423e42aba',
				'label' => 'Ages',
				'name' => 'ages',
				'type' => 'text',
				'instructions' => 'Optional',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_534f424642abb',
				'label' => 'Instructor Name',
				'name' => 'instructor_name',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_534f425542abc',
				'label' => 'Instructor Phone',
				'name' => 'instructor_phone',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_534f425a42abd',
				'label' => 'Instructor Email',
				'name' => 'instructor_email',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_534f426c42abe',
				'label' => 'Instructor Website',
				'name' => 'instructor_website',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_534f427b42abf',
				'label' => 'Description',
				'name' => 'description',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'workshop',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
				0 => 'the_content',
				1 => 'excerpt',
				2 => 'custom_fields',
				3 => 'discussion',
				4 => 'comments',
				5 => 'slug',
				6 => 'author',
				7 => 'format',
				8 => 'featured_image',
				9 => 'categories',
				10 => 'tags',
				11 => 'send-trackbacks',
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_event-fields',
		'title' => 'Event Fields',
		'fields' => array (
			array (
				'key' => 'field_52a9074f782b6',
				'label' => 'First Date',
				'name' => 'start_on',
				'type' => 'date_picker',
				'required' => 1,
				'date_format' => 'yymmdd',
				'display_format' => 'mm/dd/yy',
				'first_day' => 0,
			),
			array (
				'key' => 'field_52a90a1e782b7',
				'label' => 'Last Date',
				'name' => 'end_on',
				'type' => 'date_picker',
				'instructions' => 'Only if the event is more than one day',
				'date_format' => 'yymmdd',
				'display_format' => 'mm/dd/yy',
				'first_day' => 0,
			),
			array (
				'key' => 'field_52a90aa0782b8',
				'label' => 'Times',
				'name' => 'times',
				'type' => 'text',
				'instructions' => 'Examples:<br/>
	8:00 PM - 9:30 PM<br/>
	All Day<br/>
	Fri, Sat 8:00 PM & 10:00 PM, Sun 3:00 PM<br/>
	',
				'required' => 1,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_52a910ee80533',
				'label' => 'Image',
				'name' => 'image',
				'type' => 'image',
				'save_format' => 'url',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_52a90eecdecc6',
				'label' => 'Event Location',
				'name' => 'location',
				'type' => 'text',
				'required' => 1,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_52a90da6db80a',
				'label' => 'Google Maps Link',
				'name' => 'google_maps_link',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_52a90dcbdb80b',
				'label' => 'Description of Event',
				'name' => 'description',
				'type' => 'wysiwyg',
				'default_value' => '',
				'toolbar' => 'basic',
				'media_upload' => 'yes',
			),
			array (
				'key' => 'field_52a90de7db80c',
				'label' => 'How to get tickets',
				'name' => 'tickets_description',
				'type' => 'textarea',
				'instructions' => 'If an event is free or no advance tickets are available, just say so!',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'formatting' => 'br',
				'rows' => '',
			),
			array (
				'key' => 'field_52a90e2adb80d',
				'label' => 'Tickets Link',
				'name' => 'tickets_link',
				'type' => 'text',
				'instructions' => 'For example, a Brown Paper Tickets event link. Optional',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_52a91023decc8',
				'label' => 'Facebook Event Page Link',
				'name' => 'facebook_event_page_link',
				'type' => 'text',
				'instructions' => 'Optional',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_52a90f1edecc7',
				'label' => 'Event Contact',
				'name' => 'event_contact',
				'type' => 'textarea',
				'instructions' => 'Sometimes people have questions about tickets or other specific questions about the event. Please provide a contact name and a method of contact.',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'formatting' => 'br',
				'rows' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'event',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
				0 => 'the_content',
				1 => 'featured_image',
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_nothing',
		'title' => 'Nothing',
		'fields' => array (
			array (
				'key' => 'field_52897a5be0a6f',
				'label' => 'Placeholder Message',
				'name' => '',
				'type' => 'message',
				'message' => 'This page is a placeholder and is required for this website to work.',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page',
					'operator' => '==',
					'value' => '4',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
			array (
				array (
					'param' => 'page',
					'operator' => '==',
					'value' => '9',
					'order_no' => 0,
					'group_no' => 1,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
				0 => 'the_content',
				1 => 'excerpt',
				2 => 'custom_fields',
				3 => 'discussion',
				4 => 'comments',
				5 => 'revisions',
				6 => 'slug',
				7 => 'author',
				8 => 'format',
				9 => 'featured_image',
				10 => 'categories',
				11 => 'tags',
				12 => 'send-trackbacks',
			),
		),
		'menu_order' => 0,
	));
}
